### ISSUE TITLE
latest-canonical has not all items

### ISSUE THREAD

**Issue by rolinger1** [badlogic/heissepreise#101]
I host the project myself. Now I wanted to get the history data as written in the README, but the latest-canonical.json does not contain everything. For example "S-Budget Blue" is not in there.

**Comment by badlogic** [comment]
I just `curl -o latest-canonical.json https://heisse-preise.io/data/latest-canonical.json` then `grep S-BUDGET Blue latest-canonical.json`

Output:
```
➜  heissepreise git:(main) ✗ grep "S-BUDGET Blue" out.json 
    "name": "S-BUDGET Blue",
    "description": "Die S-BUDGET Blue Reifekurve: <br><br>3 Wochen*: Mild und frisch, etwas fester <br>2 Wochen*: Aromatisch und harmonisch-cremig <br>1 Woche*: Herzhaft und würzig, cremig ausgereift <br><br>*Vor Ablauf des Mindesthaltbarkeitsdatums.",
```

So it's definitely in there. Please check if your file has it as well. If not, fetch the latest version and restart the server.
