### ISSUE TITLE
Idea: Display categories (e.g. butter, cheese etc.) with average prices over the last 18 months

### ISSUE THREAD

**Issue by DerTimonius** [badlogic/heissepreise#113]
First of all, thanks for the great work!

While using your application I was thinking that it would be nice to display charts of certain categories on the main page. The categories could be an aggregate of multiple items in that category (like cheese, take 5 comparable items of cheese), calculate the average and display it as a graph.

Maybe (also as a possible alternative to this) there's also the possibility to add a separate category section where the user can click through different categories?

**Comment by badlogic** [comment]
Sadly, the categories aren't precise enough for this. As an alternative, one can create carts for specific product categories like milk, cheese, etc. and do charting there.
