### ISSUE TITLE
Raw data contains duplicate items for some stores

### ISSUE THREAD

**Issue by badlogic** [badlogic/heissepreise#131]
See https://heisse-preise.io/?f=-;-;-;-;-;-;-;-;-;-;-;-;-;-;100;0;-;2023-07-05;.;.;.;o.b.&l=-;.;price-asc;-&c=2023-07-05;-;2017-01-01;-;-&d=

@tiefenb any ideas?

**Comment by tiefenb** [comment]
will take a look asap

**Comment by badlogic** [comment]
Nm, it looks a couple of contributed stores have that issue. Currently working on general deduplication. Should be live in a bit.
