### ISSUE TITLE
Suggestion - Add EAN Codes

### ISSUE THREAD

**Issue by N0rimaki** [badlogic/heissepreise#141]
Add Product EAN Codes to the Database.
If not available on website, use the crowd to add and verify the codes
-next: mobile version with barcodereader for the product.

**Comment by anubister** [comment]
This would ease to build a gateway to OpenFoodFact (https://world.openfoodfacts.org/). For an app with Barcodereader, it could be reused from https://f-droid.org/en/packages/openfoodfacts.github.scrachx.openfood/ ?

**Comment by badlogic** [comment]
We've considered crowd sourcing for EANs, but that falls on its face as you're unlikely to reach a critical user mass without incentives for said user to use such an app.

Further more, building an app is something we don't have time for. In Austria, there'll be a law soon that will force stores to also publish EANs.
