### ISSUE TITLE
Rewe incomplete data

### ISSUE THREAD

**Issue by jonas-w** [badlogic/heissepreise#143]
The rewe API you fetch is limited to one store "440405" which seems to be https://www.rewe.de/marktseite/passau/440405/rewe-markt-spitalhofstr-94/

This makes the rewe data very incomplete, as it only shows products and prices for this specific store.

Is there maybe a way to check multiple stores and "merge" them together?

**Comment by badlogic** [comment]
This is on purpose for comparison reasons, as that's a store in Passau, which os close to Austria.
