### ISSUE TITLE
DM fetching returns status code 429

### ISSUE THREAD

**Issue by iantsch** [badlogic/heissepreise#15]
I guess the requests should be throttled by the Retry-After header

![image](https://github.com/badlogic/heissepreise/assets/22318501/f1e12a9e-420e-48cd-abd0-91649f3ab924)

**Comment by badlogic** [comment]
@simmac I'm totes delegating that to you, no pressure :D

**Comment by simmac** [comment]
The API doesn't return a Retry-After unfortunately...

also, I get varying results, I ran the script earlier without any 429s, yesterday I got some even when I wait 5 seconds between any requests (but that was after a few hours debugging the API, I have no idea how their limits work, so I thought exponential backoff and a bit of a fixed delay between every request was the way to go).

If you have any other ideas, let me know/feel free to implement them @iantsch, for me personally, it works good enough (maybe fetching takes one minute longer than necessary sometimes, but it works)

**Comment by iantsch** [comment]
Created a Draft PR, that will fetch the data in parallel. This also cuts the overall fetching time to the overall longest (instead of adding fetch times)
👀 @badlogic

**Comment by badlogic** [comment]
Merged. DM is indeed weird. Managed to fetch without timeout within 30 secs. I think the back off is fine as is. Closing this down.
