### ISSUE TITLE
[UX] It's often hard to reach the footer

### ISSUE THREAD

**Issue by rugk** [badlogic/heissepreise#152]
## STR

Open e.g. https://heisse-preise.io/changes.html?f=-;-;-;-;-;-;-;-;-;-;-;-;-;-;100;0;-;2023-09-18;.;.;.;&l=-;.;store-and-name;-&c=2023-09-18;-;-;2017-01-01;-;-&d= and try to scoll down to click/open the footer.

### What happens

The bad thing is you see it happening and you see the footer, but it is "so close, but out of reach", because you cannot click it.

## Solution

* either have no footer, but things somewhere else, like all social media sites
* or pin/"stick" it to the bottom, so it is always visible (could be too big especially on mobiles e.g. though)

**Comment by badlogic** [comment]
It's unlikely you want to access the footer while scrolling a large result lost. As such I think the current UX is fine, as the footer is easily accessible otherwise.
