### ISSUE TITLE
Add support for MPREIS

### ISSUE THREAD

**Issue by iantsch** [badlogic/heissepreise#21]
# Research
Website: [mpreis.at](https://www.mpreis.at/search/*)

Found the following APIs while browsing around

## trbo.com
[example](https://api-v4.trbo.com/s2s.php?g=%7B%22st%22%3A0%2C%22p%22%3A%22%22%2C%22t%22%3A1685042212%2C%22sh%22%3A13478%2C%22u%22%3A%2287dc8eba95e369e9e30ac216d964dec1%22%2C%22ts%22%3A0%2C%22ust%22%3A1685042212%2C%22sdt%22%3A0%2C%22sc%22%3A1%2C%22sid%22%3A%224446571611%22%2C%22pt%22%3A1%2C%22cb%22%3A%7B%22value%22%3A0%2C%22num%22%3A0%2C%22voucher%22%3A0%2C%22p%22%3A%5B%5D%7D%2C%22bw%22%3A1036%2C%22bh%22%3A1057%2C%22cic%22%3A%5B%5D%2C%22cic2%22%3A%7B%7D%2C%22ref%22%3A%22%22%7D&&s=%5B%5D&&p=%7B%7D&&cp=%5B%22841059%22%5D&&dl=%7B%22fetch_data%22%3A%22y%22%2C%22slider%22%3A%22pdp%22%2C%22storeID%22%3A%22NA%22%2C%22onlineStoreId%22%3A%22NA%22%7D&&seg=%5B%5D)

used to get related products on the site, no token required

## emporix.io
[developers guide](https://developer.emporix.io)

used to fetch search results (40 per page). requires token

Please add additional findings here. 

## Foodora Shop
[link](https://www.foodora.at/en/shop/yyl4/mpreis)

**Comment by simmac** [comment]
I found an Algolia-API in the network traces during browsing/searching. The URL contains the API token that is required, so I just copied the URL (see the code in #22)
