### ISSUE TITLE
Mpreis Grundpreis statt preis

### ISSUE THREAD

**Issue by J0s3f** [badlogic/heissepreise#24]
![Screenshot_2023-05-26-11-27-33-152_com brave browser-edit](https://github.com/badlogic/heissepreise/assets/604089/5d611a40-61b8-4551-86da-48558aa6f461)
https://www.mpreis.at/shop/p/hubers-bio-hendl-filet-746948

Es wird hier der Preis pro kg anstatt dem richtigen Preis genutzt.
Ich nehme an, das soll nicht so sein?

**Comment by iantsch** [comment]
Actually this is wrong in the provided data
![image](https://github.com/badlogic/heissepreise/assets/22318501/f19bfc0f-776a-417a-9c72-5a339d9b4097)

Maybe we should use originalAmount and fix it to two decimals?

**Comment by J0s3f** [comment]
Oh, then sorry for bothering you. I wonder where the correct price on the website is coming from then 🤔

**Comment by iantsch** [comment]
Seems to be fixed now
![image](https://github.com/badlogic/heissepreise/assets/22318501/7ab27bfb-a273-4966-91b8-2781da65f78f)

👀 @badlogic

**Comment by mhochsteger** [comment]
Yes, that's fixed with PR #10. The current implementation is now using `presentationPrice` for weighted articles: 
https://github.com/badlogic/heissepreise/blob/28018de7515dd1c9879406effd60b19734a7feb3/stores/mpreis.js#L26
