### ISSUE TITLE
Wrong Mpreis data?

### ISSUE THREAD

**Issue by rolinger1** [badlogic/heissepreise#30]
On the aktionen page there are items shown which are not returned by the API endpoint of the Mpreis implementation.

Where does this data come from? Is that an error?

![image](https://github.com/badlogic/heissepreise/assets/134836232/6965286a-b1f4-47dc-97ad-e48455ad8b7c)
![image](https://github.com/badlogic/heissepreise/assets/134836232/b18b47cc-8063-4dee-9603-cbab282432df)

**Comment by iantsch** [comment]
Pagination, there are several pages of results

**Comment by badlogic** [comment]
Guess we can close this out?
