### ISSUE TITLE
Various issues in unit unificiation

### ISSUE THREAD

**Issue by badlogic** [badlogic/heissepreise#37]
"Apfel Tasse" given in 100g is weird:

<img width="946" alt="Screenshot 2023-05-29 at 12 00 25" src="https://github.com/badlogic/heissepreise/assets/514052/b00ba2bb-1f6f-4721-af21-af853a1ec11b">

Same for Rispentomaten:

![Uploading Screenshot 2023-05-29 at 12.06.08.png…]()

Not sure there's a solution for this.

**Comment by badlogic** [comment]
Spar units are kind of fucked for some products. Should be 250ml, is 200ml.
<img width="926" alt="Screenshot 2023-05-31 at 17 08 48" src="https://github.com/badlogic/heissepreise/assets/514052/da9c91eb-7c42-480b-bbae-e71ff0f28397">

**Comment by mhochsteger** [comment]
See #49 for fixing the spar units.

Concerning the hard-coded 100g base price: Does it make sense to switch from price/100g to price/kg below a certain price (like 50Cent/100g)?
Alternative: let the user select the base unit

**Comment by badlogic** [comment]
I think the latest changes are good enough.

**Comment by badlogic** [comment]
mpreis weighted items are still wonky. E.g. 

https://heisse-preise.io/?q=!isWeighted%3Dtrue%20and%20%60store%60%3D%22mpreis%22

Example:
<img width="511" alt="Screenshot 2023-06-05 at 21 46 02" src="https://github.com/badlogic/heissepreise/assets/514052/d851400f-a967-42fb-ae14-caab9a790157">

quantity is 900g, but the price is the kilo price.
https://www.mpreis.at/shop/p/zuckerhut-salat-ca-1-stueck-541201

Haven't dug into mpreis at all yet.

**Comment by badlogic** [comment]
Similar issue with Spar

<img width="572" alt="Screenshot 2023-06-05 at 22 03 59" src="https://github.com/badlogic/heissepreise/assets/514052/722c163c-c0e5-43b5-9c0e-edd6aa039e47">

**Comment by badlogic** [comment]
<img width="703" alt="Screenshot 2023-06-05 at 22 12 23" src="https://github.com/badlogic/heissepreise/assets/514052/96db06ce-de84-481a-b257-8ee399b71403">

Bunch of Spar items are super wonky on their end. Unit then defaults to 1 stk, while they are weighted.

**Comment by badlogic** [comment]
Yeah, they are loosey goosey with the unit/quantity/price data. Ah well, another day :)
