### ISSUE TITLE
Compression improvements

### ISSUE THREAD

**Issue by iantsch** [badlogic/heissepreise#44]
- [ ] chunk by anything else than store to avoid different sizes in compressed files
       e.g. total items / stores
- [x] ~~move all store data from utils into `store/*.js` and provide via loadItems e.g. stores.compressed.json~~ => not needed anymore, since we build now and have this data in model/stores.js
- [ ] inject the stores with decompress/compress to avoid duplication
- [x] Investigate brotli instead of gzip
- [x] #51 
- [x] Split url compress/decompress data from logic

**Comment by badlogic** [comment]
I'd chunk them by a fixed divisor, e.g. split them up in 5 equally sized
buckets.

**Comment by badlogic** [comment]
I have no idea what items 2 and 3 mean, but I had a quick looksy at Brotli on the CLI. Behold:

```bash
➜  heissepreise git:(main) ✗ ls -lah data-tmp/*.br
-rw-r--r--@ 1 badlogic  staff    88K Jun  2 17:08 data-tmp/billa-2020-03-07.json.br
-rw-r--r--@ 1 badlogic  staff    88K Jun  2 17:08 data-tmp/billa-2020-03-10.json.br
-rw-r--r--@ 1 badlogic  staff    88K Jun  2 17:08 data-tmp/billa-2020-03-17.json.br
-rw-r--r--@ 1 badlogic  staff    85K Jun  2 17:08 data-tmp/billa-2020-03-20.json.br
-rw-r--r--@ 1 badlogic  staff    86K Jun  2 17:08 data-tmp/billa-2020-03-25.json.br
-rw-r--r--@ 1 badlogic  staff    86K Jun  2 17:08 data-tmp/billa-2020-04-01.json.br
-rw-r--r--@ 1 badlogic  staff    86K Jun  2 17:08 data-tmp/billa-2020-04-10.json.br
-rw-r--r--@ 1 badlogic  staff    87K Jun  2 17:08 data-tmp/billa-2020-04-17.json.br
-rw-r--r--@ 1 badlogic  staff    87K Jun  2 17:08 data-tmp/billa-2020-04-23.json.br
-rw-r--r--@ 1 badlogic  staff    88K Jun  2 17:08 data-tmp/billa-2020-04-28.json.br
-rw-r--r--@ 1 badlogic  staff    88K Jun  2 17:08 data-tmp/billa-2020-05-06.json.br
-rw-r--r--@ 1 badlogic  staff    89K Jun  2 17:08 data-tmp/billa-2020-05-13.json.br
-rw-r--r--@ 1 badlogic  staff    89K Jun  2 17:08 data-tmp/billa-2020-05-21.json.br
-rw-r--r--@ 1 badlogic  staff    89K Jun  2 17:08 data-tmp/billa-2020-05-27.json.br
-rw-r--r--@ 1 badlogic  staff    89K Jun  2 17:08 data-tmp/billa-2020-06-04.json.br
-rw-r--r--@ 1 badlogic  staff    89K Jun  2 17:08 data-tmp/billa-2020-06-08.json.br
-rw-r--r--@ 1 badlogic  staff    89K Jun  2 17:08 data-tmp/billa-2020-06-17.json.br
-rw-r--r--@ 1 badlogic  staff    89K Jun  2 17:08 data-tmp/billa-2020-06-24.json.br
-rw-r--r--@ 1 badlogic  staff    90K Jun  2 17:08 data-tmp/billa-2020-07-01.json.br
-rw-r--r--@ 1 badlogic  staff    90K Jun  2 17:08 data-tmp/billa-2020-07-06.json.br
-rw-r--r--@ 1 badlogic  staff    90K Jun  2 17:08 data-tmp/billa-2020-07-13.json.br
-rw-r--r--@ 1 badlogic  staff    90K Jun  2 17:08 data-tmp/billa-2020-07-21.json.br
-rw-r--r--@ 1 badlogic  staff    90K Jun  2 17:08 data-tmp/billa-2020-07-28.json.br
-rw-------@ 1 badlogic  staff   1.0M Jun  2 21:34 data-tmp/billa-2023-05-15.json.br
```

Haven't verified via decompressing, but this would be amazing. I'd take that on if you don't mind.

**Comment by badlogic** [comment]
For my raw data, gzip gives me 863mb of compressed data, brotli with quality 9 gives me 457mb, so almost a 50% reduction. Using higher quality settings becomes prohibitive, as brotli takes ages to compress the files.

I'm writing a new migration path. We'll stack the migrations going forward, should we find better ways to compress things.

**Comment by iantsch** [comment]
Awesome 😍

**Comment by badlogic** [comment]
Tada. The migration code is now a bit more generic, the same is true for readJSON and writeJSON. Changes should be mostly self-explanatory.

I've also added [migration.js](migration.js), a simple CLI tool to convert raw data between formats. Examples:

```
node migrate.js data ".json" ".json.gz"
node migrate.js data ".json.gz" ".json.br"
node migrate.js data ".json.br" ".json
```

So we can fully round trip things.

**Comment by badlogic** [comment]
Added a simple binary compression scheme. Beats json in both download size (4.8mb instead of 5mb) and decoding speed (~100ms faster)

**Comment by badlogic** [comment]
Welp, got the binary encoding down to 3.8mb. While I was working on that, I improved some general things, which lead to the json encoding now also only taking up 4mb. The json encoding now wins at load times, so it's the default again.

**Comment by iantsch** [comment]
I'm not sure we would gain anything particular by doing the other two open points, so I'm closing this issue
