### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by HannesOberreiter** [badlogic/heissepreise#58]
Project is lacking a favicon, had some time on hand to tinker on an idea. 

![favicon](https://github.com/badlogic/heissepreise/assets/16878981/2fd59a35-3d34-40ad-b3e4-e52f71203bee)

https://www.figma.com/file/WF4a4jgGocoSZoEBiewpoQ/heissepreise-favicon?type=design&node-id=0%3A1&t=S0GVx6luNr1PXNTI-1

**Comment by badlogic** [comment]
Uff, sorry you put in work. I'd like to avoid adding a gazillion files just for the fav icon. The current solution is short and simple, so we'll stick with that.

**Comment by HannesOberreiter** [comment]
Sure no worries, would have done one .svg anyway for the favicon. But nevermind, keep it simple keep it small.
