### ISSUE TITLE
No raw data for Unimarkt

### ISSUE THREAD

**Issue by mhochsteger** [badlogic/heissepreise#66]
For other other shops we return (and keep) all the raw data in `fetchData` and extract relevant information in `getCanonical`.
The Unimarkt code already extracts in `fetchData` (thus, the raw data is thrown away).

I guess this is not on purpose?

**Comment by badlogic** [comment]
Definitely not on purpose. Will fix tonight.

**Comment by badlogic** [comment]
I forgot that the Unimarkt data is an HTML scrape, not an API call. As such, there's no real raw data. We'll have to live with the raw data being the canonical data.
