### ISSUE TITLE
Generate site sources with lightweight templating

### ISSUE THREAD

**Issue by badlogic** [badlogic/heissepreise#67]
Having to modify headers in all .html is annoying. Bundling all the .js would also be nice. I'm writting a tiny site generator with the most basic templating possible. This will require restructuring of the site/ folder hierarchy.

- `site/data`: the new location of `momentum-cart.json`. We may want to add default carts or other data in the future.
- `site/js`: vendored third party JS dependencies, e.g. AlaSQL and Chart.js
- `site/`: `.html` and `.js` files for each page of the site. Also contains files beginning with an `_`, like `_header.html`.

The  generator is given the `site/` directory as an input directory, and an arbitrary output directory. It will then:

1. For each file in the input directory recursively
    1. If the file starts with `_`, ignore it
    1. Load the content of the file and replace any occurance of `%%$filename%%` with the contents of `$filename`. The `$filename` is given relative to the currently processed file
    1. Write the content to the output directory

The generator is called both by `server.js` (previously `index.js`) and `pages.js`. The server will also watch the input directory for changes and regenerate the output accordingly. The `latest-canonical.${store}.compressedjson` files will be directly written to the output directory.

No, I do not want to use a pre-existing "solution". There's nothing as lightweight out there.

RFC @iantsch @mhochsteger @simmac @pretzelhands @slhck before I fuck shit up.

**Comment by slhck** [comment]
I'm not passionate about it as I haven't worked with the code in detail. I understand not wanting to overengineer it.

I guess you will eventually want some advanced functionality like at the very least giving the included header an indication in which page it was included (e.g. to mark the current menu item as active). Unless you want to do it all in JS.

**Comment by badlogic** [comment]
I've pushed the WIP branch here. https://github.com/badlogic/heissepreise/tree/site-refactor

I removed the sticky search field CSS + observer. It was super distracting during data analysis and I could not find a use case for when it makes sense.

I'll describe how things work in the README.md or wiki once I'm done. I have one issue left concerning the table header of the cart not disappearing on mobile. Then it should be ready to merge.

**Comment by badlogic** [comment]
Alright, pretty much ready except for fixing up `pages.js`. You can try it out in this branch.
https://github.com/badlogic/heissepreise/tree/site-refactor

**Comment by badlogic** [comment]
Fuck it, we do it live. README.md update tomorrow. Basic gist:

- `template.js` is the site generator. follows what's outlined in the issue description.
- `index.js` -> `server.js`. Sorry, it was annoying me for too long.
- added live-edit to server. start like `node server.js 3000 true`. Change contents in `site/`, browser reloads tab.
