### ISSUE TITLE
Swatch conditions for Phrasen, exclusion,...

### ISSUE THREAD

**Issue by ac0815** [badlogic/heissepreise#68]
Maybe it's implemented and i just don't know about it, but it would be nice to use search patterns like "Milch -joghurt -schokolade" to narrow search result?
Or allow regular expressions?

Damn autocorrection, it should be titled search... not Swatch :(

**Comment by badlogic** [comment]
This is actually implemented, but not documented. See https://twitter.com/badlogicgames/status/1664698663757664273

I'll write up something more detailed eventually.

**Comment by ac0815** [comment]
Thanks for the hint, sufficient enough for me!
