### ISSUE TITLE
Unit calc

### ISSUE THREAD

**Issue by hausl** [badlogic/heissepreise#71]
Well, 6 x 0,5 = 3. But 6 x 0,5 **lt** sholud be **3 lt**. Not ml. May be this can be fixed somehow.
![image](https://github.com/badlogic/heissepreise/assets/5177282/1900c08c-5ca7-4096-8551-77d063920772)

**Comment by badlogic** [comment]
Hrm, now other Spar units aren't working anymore. E.g.
<img width="429" alt="Screenshot 2023-06-05 at 21 25 33" src="https://github.com/badlogic/heissepreise/assets/514052/08e3db3d-dd17-4e09-b520-6e1114bd2ae0">

is now

<img width="901" alt="Screenshot 2023-06-05 at 21 25 37" src="https://github.com/badlogic/heissepreise/assets/514052/514afd9a-816d-497e-895e-88fc85fd7898">

I see what I can do.

**Comment by mhochsteger** [comment]
Oh, I will have a look.
I should check the diff of latest-canonical in the future before creating a merge request :see_no_evil:

**Comment by mhochsteger** [comment]
@badlogic 
I can't reproduce this issue with the current main branch, is this already fixed?
