### ISSUE TITLE
Performance opportunities

### ISSUE THREAD

**Issue by slhck** [badlogic/heissepreise#85]
You have some performance opportunities per a [Lighthouse test](https://pagespeed.web.dev/analysis/https-heisse-preise-io/0diu353c8s?form_factor=mobile):

- ~~Vendor TailwindCSS to only serve the necessary styles. This is the biggest impact at the moment.~~
- Minify all JavaScripts before serving them
- Split JavaScript files into smaller bundles if they are not used on every page
- Enable caching from the server side (via express, set cache headers)

I can also have a look at one of those points.

**Comment by flobauer** [comment]
I will take a look into compiling only the necessary styles and add a rpm script for doing that.

**Comment by badlogic** [comment]
I'd rather not introduce a build tool for the time being. Tailwind.js is
17kb, which will get cached after the first fetch. Not worrying about that.

**Comment by flobauer** [comment]
This 17kb is already the compiled file, so when you add a new tailwind class like text-7xl you would have to redownload the file, because the compiling happens on the tailwind server.

**Comment by badlogic** [comment]
Jesus fucking Christ.

**Comment by flobauer** [comment]
I opened a PR #87  for a custom building. I also checked in the compiled style.css. I tried to be very non intrusive, still there are 2 extra files required.

**Comment by badlogic** [comment]
For large result sets, evaluating the new Tailwind styles and relayouting takes up to 1 second on mobile. Previously, I could display 2000 items. Any idea if this can be improved?

**Comment by slhck** [comment]
Pagination? 🙈

But I thought it's capped to 500 items?

It runs pretty smoothly for me on Firefox for Android.

**Comment by badlogic** [comment]
It's not capped in changes.html

**Comment by badlogic** [comment]
Don't sweat it, I'm eternally grateful that you're helping. The results are great, I'm just a stickler for speed. I'm using Chrom Dev Tools. You can actually see it on the desktop as well.

On the main page, type "man", while recording in the "Performance" pane. Then click "Call Tree" to see what takes up the most time.

<img width="741" alt="Screenshot 2023-06-07 at 22 28 37" src="https://github.com/badlogic/heissepreise/assets/514052/44a951fe-e34f-4f0e-94ba-19066b247c82">

**Comment by flobauer** [comment]
I transferred the atomic classes into the tailwind.css and that probably did the trick, with the compile step this is also possible now. pls check #87 

One performance reason was really the browser, who is probably calculating the result from multiple classes.

**Comment by badlogic** [comment]
Merged #87, it's a bit faster, but not by much, majority of time is still taken by style recalculation.

I guess we'll need a sort of infinite scroll implementation and not just dump all items into the DOM at once. I'll wait with that until I'm done restructuring, see #82

**Comment by badlogic** [comment]
@slhck points 2 and 3 are now solvable, as we use esbuild to bundle js per page. I'm still in the process of rewriting the 3 pages, but the end result will be tree shaken, minified bundles.

Caching is enabled on the server.

Closing this out now. Can re-open once the rewrite in #82 is complete.
