### ISSUE TITLE
Tailwind CSS Regressions

### ISSUE THREAD

**Issue by iantsch** [badlogic/heissepreise#89]
Let's discuss what we should fix, and what we are letting go:

- [x] Sticky Header not working #46
- [x] Mobile Table Headers gone #27 

see #110

**Comment by iantsch** [comment]
Sticky Headers: I'd like to get it back, my Tailwind CSS knowledge is limited.
Mobile Table Headers: Not opinionated about it.

**Comment by badlogic** [comment]
@iantsch I really, really don't like the sticky header. It gets in my way constantly.

I'm open to adding settings for that kind of stuff that we store in local storage. Suggestion:

- Little settings icon in footer
- Click on icon leads to a very very simple settings page, think old.reddit.com settings. Just a few checkboxes.
- Add a settings.js file plus Settings class to `models/` with a load() method and getters (or plain property access)
- views that have settings fetch them from the settings model. Sticky header setting would be processed by items-filter.js.

Re: mobile table headers, yeaaahhhh. I might have fucked up there. Don't know enough tailwind either.

Sorry for the late reply, repo notifications were off.

**Comment by iantsch** [comment]
I'm off again for a couple of days, will tackle both things next week. Of course if anyone else wanna tackle this... Drop a comment 🙃

**Comment by badlogic** [comment]
I just implemented the settings stuff, see

https://heisse-preise.io/settings.html, `site/settings.js/html`, and `site/models/settings.js`.

Just dump whatever settings you want in there :p

Enjoy your holidays!

**Comment by badlogic** [comment]
A sticky chart would be nice.

**Comment by iantsch** [comment]
#110 will add sticky chart and sticky search, inkluding a settings toggle (chart per default enabled, search disabled)

**Comment by iantsch** [comment]
Added missing task to the same PR, future discussion should be done in the PR, closing Issue
