### ISSUE TITLE
Unify units

### ISSUE THREAD

**Issue by mhochsteger** [badlogic/heissepreise#9]
A follow up on this comment: https://github.com/badlogic/heissepreise/pull/7#issuecomment-1555028004
> I've yet to find time to work on unit normalization. It would be very nice if one could search for units properly. You can currently enter a number as part of the search query, but it's not always effective enough.

I can have a look at the raw data processing when I have time. I guess the first step is to have some proper quantity in the canonical data, like
```json
"quantity": 125,
"unit": "g"
```
instead of 
` "unit": "125 Gramm Packung"
`

To keep it simple, I would convert the canonical data into either "g" and "ml". From that you can easily derive "Euro/kg" etc. and sort by unit price.

**Comment by mhochsteger** [comment]
See #10 for a first draft.

**Comment by badlogic** [comment]
Finally had some time to look into this a little. It's a mess. Spar has +8000 products without a unit field, where the unit may or may not be part of the product name.

Billa is sort of OKish.

Hofer is a mess too, the units are parts of the names, the units we currently store is the whole package unit.

Haven't checked DM yet.

I agree we should normalize to g/ml. However, we'll also have to store a "display unit" for lack of a better term. E.g. giving beverages >= 1l as 1000ml isn't great.

So I'd propose to have `unit` and `quantity` fields as you described, and a `displayUnit` field, which is one of `ml`, `l`, `g`, `kg`, or `Stk`, or omitted if the `unit` == `displayUnit`.

**Comment by mhochsteger** [comment]
Let's close this and continue the discussion in the Pull request.
