### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by iantsch** [badlogic/heissepreise#90]
Since we are adding different stores from different countries, should we add some localization library to allow users to view in their preferred language?

I'm usually working with [i18n](https://www.npmjs.com/package/i18n) or [i18next](https://www.npmjs.com/package/i18next)

**Comment by tiefenb** [comment]
For this case you could also use: https://tolgee.io/ (open source with option for cloud hosting service which is free for other open source projects)

**Comment by badlogic** [comment]
Scusi, but i18n is entirely out of scope for this project. I understand that we may add more non-German stores in the future, but the site is definitely aimed at German speaking people.
